### ISSUE TITLE
Local sync and unit 

### ISSUE THREAD

**Issue by bertrandlalo** [timeflux/timeflux#36]
https://github.com/timeflux/timeflux/blob/d22423d17e6e2db06535f2b8fff44f79b893f12e/timeflux/nodes/lsl.py#L142

In case `sync` is local, the offset is given in second whereas the `unit` is given in parameter, which leads to sum different units together.

**Comment by dojeda** [comment]
I think the fix is a bit less trivial than I expected. I tried setting the offset to a timedelta64[s] and the problem persisted.

**Comment by mesca** [comment]
Indeed. I have an idea of how to do it, but I will need to do extensive testing to ensure nothing is broken. How urgent is this?

**Comment by dojeda** [comment]
I guess it is a bit urgent, but we have managed to get a workaround that seems to work, by disabling the sync on all lsl inlet streams.
I only have two days of availability to test before an acquisition protocol, so if this is too tight we will stick to the workaround.
I am also worried that any new change would cause a problem since I have tested everything with v0.4 not with master.

By the way, I pushed my attempt to fix it in https://github.com/dojeda/timeflux/tree/36-lsl-sync-units in case you want to take a look
