### ISSUE TITLE
Missing environment.yml file

### ISSUE THREAD

**Issue by tonythree** [timeflux/timeflux#68]
Hello everyone, 
First of all, thanks for this beautiful project.
Trying to install Timeflux for the first time; In the Documentation - Getting started page: https://doc.timeflux.io/latest/usage/getting_started.html
There is curl to download environment.yml file: 
```
curl -O https://raw.githubusercontent.com/timeflux/timeflux/master/environment.yml
conda env create -f environment.yml

```
This file seems not to be available in the current version, and the curl returns 404: not found.
I found the environment.yml file in an older version (v0.5.0). Initiating Timeflux without this environment file and running the test.yaml, 
`timeflux -d test.yaml`
returns  No module named 'timeflux_example'.

I solved the problem by installing timeflux_example as follows:
`pip install git+https://github.com/timeflux/timeflux_example`

Either the documentation is outdated, or the environment.yml should be available again.

**Comment by mesca** [comment]
Hi Antonio,

Thank you for your message!

I removed `environment.yml` just yesterday, and have not updated the documentation yet. Currently the recommended way of installing timeflux is directly from [PyPI](https://pypi.org/project/timeflux/). We still recommend to isolate your project in a virtual environment. Not that it is absolutely required, but because it is good practice. I personally use [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html), but other solutions would work too.

Please note that I am currently implementing CI/CD pipelines on all the plugins and will deploy PyPI packages in the upcoming days. Meanwhile, you can still use the  `pip install git+https://github.com/timeflux/timeflux_[package]` command to install directly from Git.

I keep this issue opened until I fix the docs.

**Comment by mesca** [comment]
Documentation updated.
